nelmio_api_doc:
    areas:
        path_patterns:
            - ^/v1
    documentation:
        info:
            title: Routine API
            description: API for managing products and meals.
            version: 1.0.0
